# Generated by Django 5.0.1 on 2024-02-24 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='staff_id',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='sem',
            new_name='semester',
        ),
        migrations.DeleteModel(
            name='NotificationStaffs',
        ),
        migrations.DeleteModel(
            name='Staffs',
        ),
    ]
